// Command gen-mirrors generates the hand-mirror-replacing Go types from the proto
// schema (T09). It parses proto/ with protocompile (pure Go — no buf/protoc binary,
// no runtime dep on the server) and emits, in the EXISTING idiom, the bundle mirror
// structs that used to be hand-written in core/internal/bake/bundle.go, with the
// exact json tags/omitempty style so the on-disk bundle format is byte-identical
// (the Stage-0 golden gates that). Editing the generated file by hand is a CI
// failure (drift-guard: `go run ./cmd/gen-mirrors && git diff --exit-code`).
//
// Adding a proto field regenerates the mirror in one command. This is the
// glyphs.json philosophy applied to types, NOT a protobuf runtime.
package main

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bufbuild/protocompile"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// bundleMessages is the allow-list of messages mirrored into core/internal/bake
// (the ConcertBundle set). AvailableConcert* live in the httpapi edge as a separate
// hand type (concertView) and are intentionally excluded. A NEW message joins here
// deliberately; new FIELDS on these messages flow automatically.
var bundleMessages = []string{
	"PageImages", "LayerImage", "BakedSong", "MemberCues", "SongCue",
	"ConcertBundle", "BundleMember",
}

// tsMessages is the subset mirrored into the studio's TS (web/studio/src/api.gen.ts).
// The studio is the editor/REST client — it never loads a .tstage, so it needs only
// the proto types the REST surface carries; the ConcertBundle manifest is app-only
// (Kotlin, Stage 3). Every TS field is OPTIONAL: a TS mirror describes PARSED JSON,
// and with omitempty an absent field is `undefined` at runtime, so `?` is the only
// truthful type (ruled 2026-07-21).
var tsMessages = []string{"SongCue"}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-mirrors:", err)
		os.Exit(1)
	}
}

func run() error {
	// Locate the repo's proto/ dir relative to this command (core/cmd/gen-mirrors →
	// repo root/proto). Works from `go run ./cmd/gen-mirrors` in core/.
	protoRoot, err := filepath.Abs("../proto")
	if err != nil {
		return err
	}
	compiler := protocompile.Compiler{
		Resolver: protocompile.WithStandardImports(&protocompile.SourceResolver{
			ImportPaths: []string{protoRoot},
		}),
	}
	files, err := compiler.Compile(context.Background(), "troubastack/v1/bundle.proto")
	if err != nil {
		return fmt.Errorf("compile bundle.proto: %w", err)
	}
	fd := files[0]

	byName := map[string]protoreflect.MessageDescriptor{}
	msgs := fd.Messages()
	for i := 0; i < msgs.Len(); i++ {
		m := msgs.Get(i)
		byName[string(m.Name())] = m
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-mirrors from proto/troubastack/v1/bundle.proto. DO NOT EDIT.\n")
	b.WriteString("// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it).\n\n")
	b.WriteString("package bake\n\n")

	for _, name := range bundleMessages {
		m, ok := byName[name]
		if !ok {
			return fmt.Errorf("message %q not found in bundle.proto", name)
		}
		writeStruct(&b, m)
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w\n%s", err, b.String())
	}
	out := filepath.Join("internal", "bake", "bundle_gen.go")
	if err := os.WriteFile(out, src, 0o644); err != nil {
		return err
	}
	fmt.Println("wrote", out, "-", len(bundleMessages), "messages")

	// ObjectType enum → domain/objecttype_gen.go: the ONE ObjectType⇄wire-string
	// mapping, replacing the hand copies that had diverged in httpapi + sync (the
	// T51 bug that motivated T09).
	if err := genObjectType(compiler); err != nil {
		return err
	}

	// TS mirrors → web/studio/src/api.gen.ts (Stage 2a: SongCue).
	if err := genTS(byName); err != nil {
		return err
	}

	// Kotlin mirrors → app/shared/.../bundle/BundleModel.kt (Stage 3: ALL 9 messages).
	if err := genKotlin(msgs); err != nil {
		return err
	}
	return nil
}

// genKotlin emits the app's BundleModel.kt: every bundle.proto message as a
// @Serializable data class (property name == JSON name; 64-bit ints via the appended
// ProtoUInt64/Int64 serializers as canonical-JSON strings; proto3 optional → nullable;
// every field proto-defaulted). Nested messages (AvailableConcert.SongRev) become
// nested classes. The file is DO-NOT-EDIT end to end — the serializer machinery is
// generated too, fixed in the generator and regenerated, never patched in place.
func genKotlin(msgs protoreflect.MessageDescriptors) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-mirrors from proto/troubastack/v1/bundle.proto. DO NOT EDIT.\n")
	b.WriteString("// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it). The 64-bit\n")
	b.WriteString("// KSerializers at the bottom are generated machinery too — fix them in the generator,\n")
	b.WriteString("// never here. Serialization is proto3 canonical JSON: lowerCamelCase names (property ==\n")
	b.WriteString("// JSON name), int64/uint64 as JSON strings, int32 as a number, every field defaulted.\n")
	b.WriteString("package com.troubashare.shared.bundle\n\n")
	b.WriteString("import kotlinx.serialization.KSerializer\n")
	b.WriteString("import kotlinx.serialization.Serializable\n")
	b.WriteString("import kotlinx.serialization.SerializationException\n")
	b.WriteString("import kotlinx.serialization.descriptors.PrimitiveKind\n")
	b.WriteString("import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor\n")
	b.WriteString("import kotlinx.serialization.descriptors.SerialDescriptor\n")
	b.WriteString("import kotlinx.serialization.encoding.Decoder\n")
	b.WriteString("import kotlinx.serialization.encoding.Encoder\n")
	b.WriteString("import kotlinx.serialization.json.JsonDecoder\n")
	b.WriteString("import kotlinx.serialization.json.JsonPrimitive\n")

	for i := 0; i < msgs.Len(); i++ {
		b.WriteString("\n")
		writeKotlinClass(&b, msgs.Get(i), "")
	}

	b.WriteString(kotlinSerializerFooter)

	out := filepath.Join("..", "app", "shared", "src", "commonMain", "kotlin", "com",
		"troubashare", "shared", "bundle", "BundleModel.kt")
	if err := os.WriteFile(out, b.Bytes(), 0o644); err != nil {
		return err
	}
	fmt.Println("wrote", out, "-", msgs.Len(), "Kotlin classes")
	return nil
}

// writeKotlinClass emits one @Serializable data class (indented by `ind`), with any
// nested messages as nested classes in its body.
func writeKotlinClass(b *bytes.Buffer, m protoreflect.MessageDescriptor, ind string) {
	fmt.Fprintf(b, "%s/** proto %s. */\n", ind, m.FullName())
	fmt.Fprintf(b, "%s@Serializable\n%sdata class %s(\n", ind, ind, m.Name())

	fields := m.Fields()
	ordered := make([]protoreflect.FieldDescriptor, 0, fields.Len())
	for i := 0; i < fields.Len(); i++ {
		ordered = append(ordered, fields.Get(i))
	}
	sort.SliceStable(ordered, func(i, j int) bool { return ordered[i].Number() < ordered[j].Number() })
	for _, f := range ordered {
		ann, typ, def := kotlinField(f)
		fmt.Fprintf(b, "%s    %sval %s: %s = %s,\n", ind, ann, f.JSONName(), typ, def)
	}

	nested := m.Messages()
	if nested.Len() == 0 {
		fmt.Fprintf(b, "%s)\n", ind)
		return
	}
	fmt.Fprintf(b, "%s) {\n", ind)
	for i := 0; i < nested.Len(); i++ {
		b.WriteString("\n")
		writeKotlinClass(b, nested.Get(i), ind+"    ")
	}
	fmt.Fprintf(b, "%s}\n", ind)
}

// kotlinField returns the (annotation prefix, type, default) for a proto field.
func kotlinField(f protoreflect.FieldDescriptor) (ann, typ, def string) {
	if f.IsList() {
		return "", "List<" + kotlinScalarType(f) + ">", "emptyList()"
	}
	switch f.Kind() {
	case protoreflect.StringKind:
		return "", "String", `""`
	case protoreflect.BoolKind:
		if f.HasPresence() {
			return "", "Boolean?", "null" // proto3 optional
		}
		return "", "Boolean", "false"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "", "Int", "0"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "@Serializable(with = ProtoInt64Serializer::class) ", "Long", "0L"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "@Serializable(with = ProtoUInt64Serializer::class) ", "ULong", "0uL"
	case protoreflect.MessageKind:
		return "", string(f.Message().Name()), string(f.Message().Name()) + "()"
	default:
		panic("gen-mirrors: unhandled Kotlin kind " + f.Kind().String() + " on " + string(f.FullName()))
	}
}

// kotlinScalarType is the element type for a repeated field (message name or scalar).
func kotlinScalarType(f protoreflect.FieldDescriptor) string {
	switch f.Kind() {
	case protoreflect.StringKind:
		return "String"
	case protoreflect.BoolKind:
		return "Boolean"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "Int"
	case protoreflect.MessageKind:
		return string(f.Message().Name())
	default:
		panic("gen-mirrors: unhandled Kotlin list-elem kind " + f.Kind().String() + " on " + string(f.FullName()))
	}
}

// kotlinSerializerFooter is the proto3-canonical-JSON 64-bit scalar machinery, emitted
// verbatim so BundleModel.kt is a single self-contained generated file.
const kotlinSerializerFooter = `
// --- proto3 canonical-JSON scalar serializers (generated machinery — fix in the generator) ---
// int64/uint64 travel as JSON strings in canonical proto3 JSON. These read the canonical
// string form and also tolerate a bare JSON number (lenient input). A non-numeric value
// throws inside kotlinx decoding, which BundleLoader.load catches and turns into a Failed
// value — it never escapes the loader.

/** uint64 <-> JSON string. */
internal object ProtoUInt64Serializer : KSerializer<ULong> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("troubastack.uint64", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: ULong) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder): ULong = decoder.scalarString().toULong()
}

/** int64 <-> JSON string. */
internal object ProtoInt64Serializer : KSerializer<Long> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("troubastack.int64", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: Long) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder): Long = decoder.scalarString().toLong()
}

/** Read a 64-bit scalar as a string, accepting both "123" (canonical) and 123 (lenient). */
private fun Decoder.scalarString(): String =
    if (this is JsonDecoder) {
        (decodeJsonElement() as? JsonPrimitive
            ?: throw SerializationException("expected a scalar for a 64-bit integer")).content
    } else {
        decodeString()
    }
`

// genTS emits the studio's TS mirror types. Every field is OPTIONAL — a TS mirror
// types PARSED JSON, and omitempty means an absent field is `undefined` at runtime.
func genTS(byName map[string]protoreflect.MessageDescriptor) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-mirrors from proto/troubastack/v1/bundle.proto. DO NOT EDIT.\n")
	b.WriteString("// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it).\n")
	for _, name := range tsMessages {
		m, ok := byName[name]
		if !ok {
			return fmt.Errorf("TS message %q not found in bundle.proto", name)
		}
		fmt.Fprintf(&b, "\n/** %s mirrors proto %s. */\n", m.Name(), m.FullName())
		fmt.Fprintf(&b, "export type %s = {\n", m.Name())
		fields := m.Fields()
		ordered := make([]protoreflect.FieldDescriptor, 0, fields.Len())
		for i := 0; i < fields.Len(); i++ {
			ordered = append(ordered, fields.Get(i))
		}
		sort.SliceStable(ordered, func(i, j int) bool { return ordered[i].Number() < ordered[j].Number() })
		for _, f := range ordered {
			fmt.Fprintf(&b, "  %s?: %s;\n", f.JSONName(), tsType(f))
		}
		b.WriteString("};\n")
	}
	out := filepath.Join("..", "web", "studio", "src", "api.gen.ts")
	if err := os.WriteFile(out, b.Bytes(), 0o644); err != nil {
		return err
	}
	fmt.Println("wrote", out, "-", len(tsMessages), "TS types")
	return nil
}

// tsType maps a proto field to its TS type. 64-bit ints are STRINGS in the canonical
// JSON (as in the Go `,string` tags), so they type as string here too.
func tsType(f protoreflect.FieldDescriptor) string {
	var base string
	switch f.Kind() {
	case protoreflect.StringKind:
		base = "string"
	case protoreflect.BoolKind:
		base = "boolean"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		base = "number"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		base = "string" // canonical JSON encodes 64-bit ints as strings
	case protoreflect.MessageKind:
		base = string(f.Message().Name())
	default:
		panic("gen-mirrors: unhandled TS kind " + f.Kind().String() + " on " + string(f.FullName()))
	}
	if f.IsList() {
		return base + "[]"
	}
	return base
}

// genObjectType emits the domain package's ObjectType⇄string functions from the
// proto ObjectType enum. In package domain, so it references the Type* constants
// (hand-defined with matching iota values) directly — a rename there is a compile
// error, keeping the enum authoritative.
func genObjectType(compiler protocompile.Compiler) error {
	files, err := compiler.Compile(context.Background(), "troubastack/v1/object.proto")
	if err != nil {
		return fmt.Errorf("compile object.proto: %w", err)
	}
	enums := files[0].Enums()
	var e protoreflect.EnumDescriptor
	for i := 0; i < enums.Len(); i++ {
		if enums.Get(i).Name() == "ObjectType" {
			e = enums.Get(i)
			break
		}
	}
	if e == nil {
		return fmt.Errorf("ObjectType enum not found in object.proto")
	}
	prefix := screamingSnake(string(e.Name())) + "_" // OBJECT_TYPE_

	type pair struct{ konst, wire string }
	var pairs []pair
	vals := e.Values()
	for i := 0; i < vals.Len(); i++ {
		v := vals.Get(i)
		stripped := strings.TrimPrefix(string(v.Name()), prefix)
		if stripped == "UNSPECIFIED" { // the zero value maps to "" / is the default
			continue
		}
		pairs = append(pairs, pair{konst: "Type" + pascalFromScreaming(stripped), wire: strings.ToLower(stripped)})
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-mirrors from proto/troubastack/v1/object.proto. DO NOT EDIT.\n")
	b.WriteString("// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it).\n\n")
	b.WriteString("package domain\n\n")
	b.WriteString("// ObjectTypeToString maps an ObjectType to its canonical wire string\n")
	b.WriteString("// (TypeUnspecified / unknown → \"\").\n")
	b.WriteString("func ObjectTypeToString(t ObjectType) string {\n\tswitch t {\n")
	for _, p := range pairs {
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn %q\n", p.konst, p.wire)
	}
	b.WriteString("\tdefault:\n\t\treturn \"\"\n\t}\n}\n\n")
	b.WriteString("// ObjectTypeFromString maps a wire string to its ObjectType\n")
	b.WriteString("// (unknown → TypeUnspecified).\n")
	b.WriteString("func ObjectTypeFromString(s string) ObjectType {\n\tswitch s {\n")
	for _, p := range pairs {
		fmt.Fprintf(&b, "\tcase %q:\n\t\treturn %s\n", p.wire, p.konst)
	}
	b.WriteString("\tdefault:\n\t\treturn TypeUnspecified\n\t}\n}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt objecttype: %w\n%s", err, b.String())
	}
	out := filepath.Join("internal", "domain", "objecttype_gen.go")
	if err := os.WriteFile(out, src, 0o644); err != nil {
		return err
	}
	fmt.Println("wrote", out, "-", len(pairs), "object types")

	// Same enum → the TS wire union in ink (T09 Stage 2b). ink's InkObjectType is
	// this union PLUS the dev-only "arrow" (reconciled in ink/src/index.ts); studio's
	// AnnotationObject.type is this wire set directly. Kills the stale api.ts union.
	var ts bytes.Buffer
	ts.WriteString("// Code generated by cmd/gen-mirrors from proto/troubastack/v1/object.proto. DO NOT EDIT.\n")
	ts.WriteString("// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it).\n\n")
	ts.WriteString("/** The wire object-type set — mirrors proto ObjectType. */\n")
	ts.WriteString("export type ObjectType =\n")
	for _, p := range pairs {
		fmt.Fprintf(&ts, "  | %q\n", p.wire)
	}
	// trim the trailing newline, add the semicolon
	tsSrc := strings.TrimRight(ts.String(), "\n") + ";\n"
	tsOut := filepath.Join("..", "web", "ink", "src", "objecttype.gen.ts")
	if err := os.WriteFile(tsOut, []byte(tsSrc), 0o644); err != nil {
		return err
	}
	fmt.Println("wrote", tsOut, "-", len(pairs), "wire types")
	return nil
}

// screamingSnake converts a PascalCase proto name to its SCREAMING_SNAKE enum
// prefix (ObjectType → OBJECT_TYPE).
func screamingSnake(pascal string) string {
	var b strings.Builder
	for i, r := range pascal {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		b.WriteRune(r)
	}
	return strings.ToUpper(b.String())
}

// pascalFromScreaming converts a SCREAMING_SNAKE segment set to PascalCase
// (FREEHAND → Freehand, FOO_BAR → FooBar).
func pascalFromScreaming(s string) string {
	var b strings.Builder
	for _, seg := range strings.Split(s, "_") {
		if seg == "" {
			continue
		}
		b.WriteString(strings.ToUpper(seg[:1]) + strings.ToLower(seg[1:]))
	}
	return b.String()
}

// writeStruct emits one Go struct mirroring a proto message, fields in field-number
// order, with the project's json-tag conventions.
func writeStruct(b *bytes.Buffer, m protoreflect.MessageDescriptor) {
	fmt.Fprintf(b, "// %s mirrors proto %s.\n", m.Name(), m.FullName())
	fmt.Fprintf(b, "type %s struct {\n", m.Name())

	fields := m.Fields()
	ordered := make([]protoreflect.FieldDescriptor, 0, fields.Len())
	for i := 0; i < fields.Len(); i++ {
		ordered = append(ordered, fields.Get(i))
	}
	sort.SliceStable(ordered, func(i, j int) bool { return ordered[i].Number() < ordered[j].Number() })

	for _, f := range ordered {
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", goFieldName(f.Name()), goType(f), jsonTag(f))
	}
	b.WriteString("}\n\n")
}

// goFieldName PascalCases a proto snake_case field name, honoring the Go "ID"
// initialism (song_id → SongID) — the only initialism in this schema.
func goFieldName(n protoreflect.Name) string {
	var out strings.Builder
	for _, seg := range strings.Split(string(n), "_") {
		if seg == "" {
			continue
		}
		if seg == "id" {
			out.WriteString("ID")
			continue
		}
		out.WriteString(strings.ToUpper(seg[:1]) + seg[1:])
	}
	return out.String()
}

// goType maps a proto field to its Go mirror type: repeated → slice, proto3
// `optional` scalar → pointer (presence), message → the mirror struct name.
func goType(f protoreflect.FieldDescriptor) string {
	base := scalarGoType(f)
	if f.IsList() {
		return "[]" + base
	}
	if f.HasPresence() && f.Kind() != protoreflect.MessageKind {
		return "*" + base // proto3 optional scalar → pointer
	}
	return base
}

func scalarGoType(f protoreflect.FieldDescriptor) string {
	switch f.Kind() {
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.MessageKind:
		return string(f.Message().Name())
	default:
		panic("gen-mirrors: unhandled proto kind " + f.Kind().String() + " on " + string(f.FullName()))
	}
}

// jsonTag builds the struct tag: camelCase name (proto JSONName), `,string` for
// 64-bit ints (canonical JSON encodes them as strings), always `,omitempty`.
func jsonTag(f protoreflect.FieldDescriptor) string {
	tag := f.JSONName()
	switch f.Kind() {
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		if !f.IsList() {
			tag += ",string"
		}
	}
	return tag + ",omitempty"
}
