// Command gen-mirrors generates the hand-mirror-replacing Go types from the proto
// schema (T09). It parses proto/ with protocompile (pure Go — no buf/protoc binary,
// no runtime dep on the server) and emits, in the EXISTING idiom, the bundle mirror
// structs that used to be hand-written in core/internal/bake/bundle.go, with the
// exact json tags/omitempty style so the on-disk bundle format is byte-identical
// (the Stage-0 golden gates that). Editing the generated file by hand is a CI
// failure (drift-guard: `go run ./cmd/gen-mirrors && git diff --exit-code`).
//
// Adding a proto field regenerates the mirror in one command. This is the
// glyphs.json philosophy applied to types, NOT a protobuf runtime.
package main

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bufbuild/protocompile"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// bundleMessages is the allow-list of messages mirrored into core/internal/bake
// (the ConcertBundle set). AvailableConcert* live in the httpapi edge as a separate
// hand type (concertView) and are intentionally excluded. A NEW message joins here
// deliberately; new FIELDS on these messages flow automatically.
var bundleMessages = []string{
	"PageImages", "LayerImage", "BakedSong", "MemberCues", "SongCue",
	"ConcertBundle", "BundleMember",
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-mirrors:", err)
		os.Exit(1)
	}
}

func run() error {
	// Locate the repo's proto/ dir relative to this command (core/cmd/gen-mirrors →
	// repo root/proto). Works from `go run ./cmd/gen-mirrors` in core/.
	protoRoot, err := filepath.Abs("../proto")
	if err != nil {
		return err
	}
	compiler := protocompile.Compiler{
		Resolver: protocompile.WithStandardImports(&protocompile.SourceResolver{
			ImportPaths: []string{protoRoot},
		}),
	}
	files, err := compiler.Compile(context.Background(), "troubastack/v1/bundle.proto")
	if err != nil {
		return fmt.Errorf("compile bundle.proto: %w", err)
	}
	fd := files[0]

	byName := map[string]protoreflect.MessageDescriptor{}
	msgs := fd.Messages()
	for i := 0; i < msgs.Len(); i++ {
		m := msgs.Get(i)
		byName[string(m.Name())] = m
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-mirrors from proto/troubastack/v1/bundle.proto. DO NOT EDIT.\n")
	b.WriteString("// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it).\n\n")
	b.WriteString("package bake\n\n")

	for _, name := range bundleMessages {
		m, ok := byName[name]
		if !ok {
			return fmt.Errorf("message %q not found in bundle.proto", name)
		}
		writeStruct(&b, m)
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w\n%s", err, b.String())
	}
	out := filepath.Join("internal", "bake", "bundle_gen.go")
	if err := os.WriteFile(out, src, 0o644); err != nil {
		return err
	}
	fmt.Println("wrote", out, "-", len(bundleMessages), "messages")
	return nil
}

// writeStruct emits one Go struct mirroring a proto message, fields in field-number
// order, with the project's json-tag conventions.
func writeStruct(b *bytes.Buffer, m protoreflect.MessageDescriptor) {
	fmt.Fprintf(b, "// %s mirrors proto %s.\n", m.Name(), m.FullName())
	fmt.Fprintf(b, "type %s struct {\n", m.Name())

	fields := m.Fields()
	ordered := make([]protoreflect.FieldDescriptor, 0, fields.Len())
	for i := 0; i < fields.Len(); i++ {
		ordered = append(ordered, fields.Get(i))
	}
	sort.SliceStable(ordered, func(i, j int) bool { return ordered[i].Number() < ordered[j].Number() })

	for _, f := range ordered {
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", goFieldName(f.Name()), goType(f), jsonTag(f))
	}
	b.WriteString("}\n\n")
}

// goFieldName PascalCases a proto snake_case field name, honoring the Go "ID"
// initialism (song_id → SongID) — the only initialism in this schema.
func goFieldName(n protoreflect.Name) string {
	var out strings.Builder
	for _, seg := range strings.Split(string(n), "_") {
		if seg == "" {
			continue
		}
		if seg == "id" {
			out.WriteString("ID")
			continue
		}
		out.WriteString(strings.ToUpper(seg[:1]) + seg[1:])
	}
	return out.String()
}

// goType maps a proto field to its Go mirror type: repeated → slice, proto3
// `optional` scalar → pointer (presence), message → the mirror struct name.
func goType(f protoreflect.FieldDescriptor) string {
	base := scalarGoType(f)
	if f.IsList() {
		return "[]" + base
	}
	if f.HasPresence() && f.Kind() != protoreflect.MessageKind {
		return "*" + base // proto3 optional scalar → pointer
	}
	return base
}

func scalarGoType(f protoreflect.FieldDescriptor) string {
	switch f.Kind() {
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.MessageKind:
		return string(f.Message().Name())
	default:
		panic("gen-mirrors: unhandled proto kind " + f.Kind().String() + " on " + string(f.FullName()))
	}
}

// jsonTag builds the struct tag: camelCase name (proto JSONName), `,string` for
// 64-bit ints (canonical JSON encodes them as strings), always `,omitempty`.
func jsonTag(f protoreflect.FieldDescriptor) string {
	tag := f.JSONName()
	switch f.Kind() {
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		if !f.IsList() {
			tag += ",string"
		}
	}
	return tag + ",omitempty"
}
