// Command seed populates a running TroubaCore server with a demo dataset — users,
// bands, an orchestra, songs, sheet-music, and layered annotations — then prints a
// guide for browsing it.
//
// T134 phase 2 (stage C): each band is now seeded by building its CANONICAL v2 band
// directory (a demo group in memory from the Go literals; a real band by migrating
// its folder on read), packing it to a .tband, and POSTing it to the import endpoint
// — one path for the demo and real bands. Import FIRST, passwords SECOND (⟨P8⟩): the
// admin is registered as the importer, everyone else arrives via import (personal
// content intact) and is then given a password over the public reset flow. What a
// file cannot carry — passwords — is all that stays in the seeder.
//
// PDFs are read from docs/demo-charts (or generated as a fallback), so the seed never
// fails for lack of internet; a user/band that already exists is reused.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	addr := flag.String("addr", "http://localhost:8080", "base URL of the running troubacore server")
	password := flag.String("password", "demo", "password set for every demo user")
	only := flag.String("only", "", "seed only groups whose name contains this substring (case-insensitive), plus just their members; e.g. -only orchestra. Empty = seed everything.")
	var bands multiFlag
	flag.Var(&bands, "band", "seed only the local band(s) (bands/*/band.json) whose shortname matches; repeatable, e.g. -band myband -band otherband. Used by `make band=<shortname>` (make splits a comma list into repeated -band flags).")
	dumpImports := flag.String("dump-imports", "", "write each demo chart's exact annotation import payload to this dir (offline, no server) and exit — provenance for docs/demo-charts/*.annotations.json (B13).")
	flag.Parse()

	if *dumpImports != "" {
		if err := runDumpImports(*dumpImports); err != nil {
			log.Fatalf("seed -dump-imports: %v", err)
		}
		return
	}

	if err := run(*addr, *password, *only, bands); err != nil {
		log.Fatalf("seed: %v", err)
	}
}

// multiFlag collects a repeatable string flag (e.g. -band myband -band otherband) into a slice.
// Each occurrence is one value — commas are NOT split, so `-band otherband,myband` stays a single
// (unmatched) shortname rather than silently meaning two bands.
type multiFlag []string

func (m *multiFlag) String() string { return strings.Join(*m, ",") }
func (m *multiFlag) Set(v string) error {
	*m = append(*m, v)
	return nil
}

// runDumpImports builds every demo chart's annotation import offline (placeholder ids + the
// committed anchor manifests) and writes <chart>.annotations.json — the provenance source for
// the tracked docs, never hand-edited (B13 §6).
func runDumpImports(dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	u := map[string]string{"marie": "marie", "leo": "leo", "sasha": "sasha", "ivan": "ivan", "cory": "cory", "flora": "flora"}
	note := "GENERATED by `go run ./cmd/seed -dump-imports` from the cmd/seed builders + " +
		"docs/demo-charts/*.anchors.json (B13). Do NOT hand-edit — regenerate. Coords are page-" +
		"relative [0,1]; ids are the seed's stable derivations. This is the exact payload the seed " +
		"POSTs to .../annotations/import."
	type doc struct {
		Note    string       `json:"//"`
		Layers  []wireLayer  `json:"layers"`
		Objects []wireObject `json:"objects"`
	}
	charts := []struct {
		name string
		im   annotationsImport
	}{
		{"open-road", buildOpenRoadAnnotations("open-road", "leadsheet", u, "leo", mustAnchors("open-road-leadsheet"))},
		{"open-road-guitar", buildOpenRoadGuitarAnnotations("open-road", "guitar", u, "leo", mustAnchors("open-road-guitar"))},
		{"house-rising-sun-tab", buildBandChartAnnotations("house", "tab", "House of the Rising Sun", u, "leo", mustAnchors("house-rising-sun-tab"))},
		{"house-rising-sun-drums", buildDrumPartAnnotations("house", "drums", mustAnchors("house-rising-sun-drums"))},
		{"amazing-grace", buildBandChartAnnotations("grace", "ls", "Amazing Grace", u, "leo", mustAnchors("amazing-grace"))},
		{"greensleeves", buildBandChartAnnotations("greensleeves", "gs", "Greensleeves", u, "leo", mustAnchors("greensleeves"))},
		{"ek-violin1", buildEineKleineAnnotations("ek", "vln1", u, "flora", mustAnchors("ek-violin1"))},
		{"ek-score", buildScoreConductorAnnotations("ek", "score", "ek", "flora", mustAnchors("ek-score"))},
		{"canon-violin1", buildCanonAnnotations("canon", "vln1", u, "flora", mustAnchors("canon-violin1"))},
		{"canon-score", buildScoreConductorAnnotations("canon", "score", "canon", "flora", mustAnchors("canon-score"))},
	}
	for _, c := range charts {
		b, err := json.MarshalIndent(doc{Note: note, Layers: c.im.Layers, Objects: c.im.Objects}, "", "  ")
		if err != nil {
			return err
		}
		p := filepath.Join(dir, c.name+".annotations.json")
		if err := os.WriteFile(p, append(b, '\n'), 0o644); err != nil {
			return err
		}
		fmt.Printf("wrote %s (%d layers, %d objects)\n", p, len(c.im.Layers), len(c.im.Objects))
	}
	return nil
}

// person is a demo user definition.
type person struct {
	username string
	display  string
	role     string // human-readable role label for the guide (instrument/part)
}

// songDef pairs a song title/artist + settable metadata with its PDF source(s).
//
// A song normally has one shared PDF (src). To showcase the multi-file /
// per-member "my files" feature, a song may instead define several pool files
// (files): each is uploaded to the shared pool with a distinct human title
// (pdfSource.docTitle). When files is set it takes precedence over src.
//
// myFilesFor curates a specific member's PERSONAL ordered selection over those
// pool files: keyed by username, the value is a list of indices into files in
// the exact order that member should see them (a non-default subset+order). The
// seeder PUTs this via the my-files endpoint as that user.
type songDef struct {
	title  string
	artist string
	// slug is the song's identity inside a LOCAL band folder (bands/<band>/<slug>/) — the key
	// setlists.json references (T100). Empty for demo songs, which have no folder.
	slug       string
	key        string // musical key (settable on the song page)
	tempo      int    // BPM
	meter      string // T86: metre "N/D" ("" = 4/4)
	tags       []string
	notes      string
	src        pdfSource
	files      []pdfSource      // optional multi-file shared pool (overrides src)
	myFilesFor map[string][]int // username -> ordered indices into files (custom my-files)
	// cuesFor seeds each member's PERSONAL song cues (T50): username -> that member's
	// ordered icon+color list. Self-only, so the seeder PUTs each list as that user;
	// they ride the member's per-member bake (visible when baking "my parts").
	cuesFor map[string][]cueDef
	// textCharts are folder-discovered chart parts (B15): each bands/<band>/<slug>/*.txt becomes a
	// text-chart part named after the file (lyrics.txt first, then sorted). Used by local bands;
	// demo songs use textChartPath below.
	textCharts []textPart // (textPart defined below)
	// textChartPath is an optional committed chart-dialect source (docs/demo-charts/*.chart)
	// added to the pool as a REAL text chart (T19) — POST /text-charts renders it to a PDF
	// server-side, so the demo shows the text-chart file type, not only uploaded PDFs (B10).
	textChartPath string
}

// textPart is one folder-discovered chart part (B15): a chart-dialect source file and the pool
// name it gets (the file's basename without .txt).
type textPart struct {
	path string
	name string
}

// cueDef is one personal song cue (T50): a curated glyph id + an optional "#rrggbb"
// tint ("" = neutral). See docs/tasks/T50-song-cues.md §2 for the id set.
type cueDef struct {
	icon  string
	color string
}

// overrideDef is a per-setlist-item override (settable on the setlist page).
type overrideDef struct {
	song            string // song title to match
	keyOverride     string
	tempoOverride   int
	notes           string
	onCall          bool // T100: mirrors .tband manifestItem.onCall
	transposeChords bool // T100: mirrors .tband manifestItem.transposeChords
}

// setlistDef is a setlist to create for a group, with optional item overrides.
type setlistDef struct {
	name      string
	eventDate string // ISO yyyy-mm-dd
	venue     string
	notes     string
	overrides []overrideDef
	// items is an EXPLICIT, ORDERED item list (T100 — a local band's setlists.json). When set it
	// replaces "every song the group has, in group order": a gig is a SUBSET in a chosen order, and
	// each entry may carry the same overrides. Empty ⇒ the demo behaviour, unchanged.
	items []overrideDef
}

// groupDef is a band or orchestra to create.
type groupDef struct {
	name      string
	kind      string // "Band" or "Orchestra" (label only)
	admin     string // username of the admin/owner
	members   []string
	conductor string // optional: a member to promote to the "conductor" role
	songs     []songDef
	setlists  []setlistDef
	// personal marks a REAL (non-demo) band (discovered from bands/*/band.json) that must stay
	// OUT of the public demo seed: it is skipped by a plain `seed`/`make demo` run and only built
	// when explicitly selected (`-only <name>` or `-band <shortname>`). Its members are likewise
	// registered only then.
	personal bool
	// shortname is the band.json "shortname" — a stable handle for `make band=<shortname>`.
	shortname string
	// folderPath is a local band's on-disk directory (T134 phase 2): the seeder migrates it on read
	// (legacy→canonical) → packs → imports, instead of driving the per-call REST sequence. "" for demo
	// groups, which build their canonical directory in memory from the Go literals (groupToCanonical).
	folderPath string
}

func run(addr, password, only string, bands []string) error {
	if err := ensureAssetsDir(); err != nil {
		return err
	}

	people := []person{
		{"marie", "Marie", "singer (band admin)"},
		{"leo", "Leo", "guitar"},
		{"sasha", "Sasha", "bass"},
		{"maestro", "Anya", "conductor (orchestra admin)"},
		{"flora", "Flora", "conductor"},
		{"cory", "Cory", "cello"},
		// String section — one player per desk so every part has an owner.
		{"ivan", "Ivan", "violin I"},
		{"vera", "Vera", "violin II"},
		{"mila", "Mila", "viola / violin III"},
	}

	groups := []groupDef{
		{
			name:      "The Troubadours",
			kind:      "Band",
			admin:     "marie",
			members:   []string{"leo", "sasha"},
			conductor: "leo", // promoted to the conductor role; owns the conductor cues
			songs: []songDef{
				// An ORIGINAL demo song with a REAL committed chart (lead sheet + guitar
				// tab) from docs/demo-charts — the FLAGSHIP annotation showcase (see
				// buildOpenRoadAnnotations). All demo content is copyright-safe: original
				// or public-domain (DEMO-VID Part A) — no copyrighted song titles/lyrics.
				{title: "The Open Road", artist: "", key: "G", tempo: 92, meter: "4/4", tags: []string{"original", "demo"}, notes: "Original demo song — lead sheet + a guitarist's intro-riff sheet. Capo 2.",
					files: []pdfSource{
						{cacheName: "open-road-leadsheet.pdf", localPath: "../docs/demo-charts/open-road-leadsheet.pdf", docTitle: "Lead sheet", title: "The Open Road", subtitle: "original demo song", pages: 2},
						{cacheName: "open-road-guitar.pdf", localPath: "../docs/demo-charts/open-road-guitar.pdf", docTitle: "Guitar", title: "The Open Road — Guitar", subtitle: "intro riff", pages: 1},
					},
					// A REAL text chart alongside the PDFs — the demo shows the T19 chart type
					// (server-rendered from chart-dialect source), not only PDFs (B10).
					textChartPath: "../docs/demo-charts/open-road-lyrics.chart",
					// Personal cues (T50): Marie sings + plays the RED electric (VLL's canonical
					// "mic + red guitar" example, shown per-member on setlist rows + in the app).
					cuesFor: map[string][]cueDef{
						"marie": {{icon: "mic"}, {icon: "guitar-electric", color: "#e11d48"}},
						"leo":   {{icon: "guitar-acoustic"}},
						"sasha": {{icon: "bass", color: "#2563eb"}},
					}},
				// TRADITIONAL / PUBLIC DOMAIN — the MULTI-FILE showcase: real committed
				// parts (a guitar tab + a drum groove) PLUS a rendered chord chart (text
				// chart). Members curate their own "my files" view; parts carry their own
				// per-file annotations (B11). Replaces the old copyrighted multi-file song.
				{title: "House of the Rising Sun", artist: "Traditional", key: "Am", tempo: 72, meter: "6/8", tags: []string{"folk", "public-domain"}, notes: "Traditional; soft 6/8, let the arpeggio ring.",
					files: []pdfSource{
						{cacheName: "house-rising-sun-tab.pdf", localPath: "../docs/demo-charts/house-rising-sun-tab.pdf", docTitle: "Guitar tab", title: "House of the Rising Sun — Guitar", subtitle: "traditional (guitar tab)", pages: 1},
						{cacheName: "house-rising-sun-drums.pdf", localPath: "../docs/demo-charts/house-rising-sun-drums.pdf", docTitle: "Drums", title: "House of the Rising Sun — Drums", subtitle: "traditional (drum groove)", pages: 1},
					},
					// The rendered chord chart (lead sheet) joins the pool after the parts.
					textChartPath: "../docs/demo-charts/house-of-the-rising-sun.chart",
					// Leo (guitar) curates his own focused view: just the guitar tab.
					myFilesFor: map[string][]int{
						"leo": {0},
					},
					cuesFor: map[string][]cueDef{
						"marie": {{icon: "mic"}},
						"leo":   {{icon: "guitar-acoustic"}},
						"sasha": {{icon: "bass", color: "#2563eb"}},
					}},
				// PUBLIC DOMAIN hymn (John Newton, 1779). T95 Stage B: its lead sheet is the
				// chart-dialect source amazing-grace.chart, rendered through chartpdf (mkcharts
				// regenerates amazing-grace.pdf from it) — no longer a duplicate hand-drawn mkcharts
				// chart plus a separate text chart.
				{title: "Amazing Grace", artist: "Traditional", key: "G", tempo: 72, meter: "3/4", tags: []string{"hymn", "public-domain"}, notes: "Newton, 1779; gentle 3/4.",
					src: pdfSource{cacheName: "amazing-grace.pdf", localPath: "../docs/demo-charts/amazing-grace.pdf", docTitle: "Lead sheet", title: "Amazing Grace", subtitle: "words: John Newton, 1779 (public domain)", pages: 1},
					cuesFor: map[string][]cueDef{
						"marie": {{icon: "mic"}},
						"sasha": {{icon: "keys", color: "#7c3aed"}},
					}},
				// A REAL published folk edition (Mutopia): Greensleeves for voice + guitar (melody,
				// lyrics, guitar tab). Music is public domain; the typeset is CC-BY-SA 4.0 (© 2014
				// David Kastrup, Mutopia) — attributed in docs/demo-charts/README.md.
				{title: "Greensleeves", artist: "Traditional", key: "Am", tempo: 90, meter: "3/4", tags: []string{"folk", "creative-commons"}, notes: "Traditional English; 3/4, flowing.",
					src: pdfSource{cacheName: "greensleeves.pdf", localPath: "../docs/demo-charts/greensleeves.pdf", docTitle: "Voice + guitar", title: "Greensleeves", subtitle: "traditional (Mutopia · David Kastrup, CC-BY-SA 4.0)", pages: 2},
					cuesFor: map[string][]cueDef{
						"marie": {{icon: "mic"}},
						"leo":   {{icon: "guitar-acoustic"}},
					}},
			},
			setlists: []setlistDef{{
				name: "Sat @ The Anchor", eventDate: "2026-07-04", venue: "The Anchor Pub", notes: "60-minute set.",
				overrides: []overrideDef{
					{song: "House of the Rising Sun", keyOverride: "Bm", notes: "Lift it a tone for the room."},
					{song: "The Open Road", notes: "Encore — everyone in on the last chorus."},
				},
			}},
		},
		{
			name:      "City Chamber Orchestra",
			kind:      "Orchestra",
			admin:     "maestro",
			members:   []string{"flora", "cory", "ivan", "vera", "mila"},
			conductor: "flora", // promoted to the "conductor" role to show role management
			songs: []songDef{
				{title: "Eine kleine Nachtmusik", artist: "W. A. Mozart", key: "G", tempo: 140, tags: []string{"classical", "public-domain"}, notes: "Allegro; K. 525 (1st mvt).",
					// REAL, complete PUBLIC-DOMAIN edition (Mutopia Project, LilyPond typeset): the
					// full 1st movement as a conductor's full score + separate string parts. Players
					// open their desk's part; the conductor marks up the score. Committed PDFs.
					files: []pdfSource{
						{cacheName: "ek-violin1.pdf", localPath: "../docs/demo-charts/ek-violin1.pdf", docTitle: "Violin I", title: "Eine kleine Nachtmusik — Violin I", subtitle: "Mozart K.525", pages: 3},
						{cacheName: "ek-violin2.pdf", localPath: "../docs/demo-charts/ek-violin2.pdf", docTitle: "Violin II", title: "Eine kleine Nachtmusik — Violin II", subtitle: "Mozart K.525", pages: 2},
						{cacheName: "ek-viola.pdf", localPath: "../docs/demo-charts/ek-viola.pdf", docTitle: "Viola", title: "Eine kleine Nachtmusik — Viola", subtitle: "Mozart K.525", pages: 2},
						{cacheName: "ek-cello.pdf", localPath: "../docs/demo-charts/ek-cello.pdf", docTitle: "Cello", title: "Eine kleine Nachtmusik — Cello", subtitle: "Mozart K.525", pages: 2},
						{cacheName: "ek-score.pdf", localPath: "../docs/demo-charts/ek-score.pdf", docTitle: "Full score", title: "Eine kleine Nachtmusik — Score", subtitle: "Mozart K.525 (conductor)", pages: 5},
					},
					// Each player curates their own desk's part (Ivan=Vln I, Vera=Vln II, Mila=Viola,
					// Cory=Cello); the conductor works from the full score.
					myFilesFor: map[string][]int{"ivan": {0}, "vera": {1}, "mila": {2}, "cory": {3}}},
				// Pachelbel, 1680 — the orchestra's MULTI-PART showcase. REAL, complete edition
				// (Mutopia Project "Canon per 3 Violini e Basso", LilyPond typeset): a conductor's
				// full score + the four parts (Violin I/II/III + Cello). The music is public domain;
				// the TYPESET EDITION is CC-BY 4.0 (© 2015 Michael Fischer v. Mollard, Mutopia) —
				// attributed in docs/demo-charts/README.md. Committed PDFs.
				{title: "Canon in D", artist: "J. Pachelbel", key: "D", tempo: 56, tags: []string{"classical", "creative-commons"}, notes: "Canon over the famous ground bass.",
					files: []pdfSource{
						{cacheName: "canon-violin1.pdf", localPath: "../docs/demo-charts/canon-violin1.pdf", docTitle: "Violin I", title: "Canon in D — Violin I", subtitle: "Pachelbel", pages: 2},
						{cacheName: "canon-violin2.pdf", localPath: "../docs/demo-charts/canon-violin2.pdf", docTitle: "Violin II", title: "Canon in D — Violin II", subtitle: "Pachelbel", pages: 2},
						{cacheName: "canon-violin3.pdf", localPath: "../docs/demo-charts/canon-violin3.pdf", docTitle: "Violin III", title: "Canon in D — Violin III", subtitle: "Pachelbel", pages: 2},
						{cacheName: "canon-cello.pdf", localPath: "../docs/demo-charts/canon-cello.pdf", docTitle: "Cello", title: "Canon in D — Cello (basso)", subtitle: "Pachelbel", pages: 1},
						{cacheName: "canon-score.pdf", localPath: "../docs/demo-charts/canon-score.pdf", docTitle: "Full score", title: "Canon in D — Score", subtitle: "Pachelbel (conductor)", pages: 6},
					},
					// Each player curates their desk's part (Ivan=Vln I, Vera=Vln II, Mila=Vln III,
					// Cory=Cello/basso); the conductor works from the full score.
					myFilesFor: map[string][]int{"ivan": {0}, "vera": {1}, "mila": {2}, "cory": {3}}},
			},
			setlists: []setlistDef{{
				name: "Spring Concert", eventDate: "2026-05-15", venue: "City Hall", notes: "Strings programme.",
				overrides: []overrideDef{
					{song: "Eine kleine Nachtmusik", tempoOverride: 132, notes: "Take the repeat."},
					{song: "Canon in D", notes: "Watch the tempo — don't rush the bass."},
				},
			}},
		},
	}

	// Local, real bands (NOT demo content) are discovered from the gitignored bands/ folder —
	// one subfolder per band (band.json + repertoire.json + per-song source files). This lets
	// any user seed THEIR own band's data locally without touching this file; the folders are
	// never committed. Each is marked `personal`, so a plain `seed`/`make demo` skips it and
	// `-band <shortname>` (e.g. `make band=<shortname>`) builds it.
	localBands, localPeople, err := loadLocalBands()
	if err != nil {
		return err
	}
	groups = append(groups, localBands...)
	people = append(people, localPeople...)

	// Decide which groups to seed and narrow the user list to their members (see selectGroups).
	groups, people, err = selectGroups(groups, people, only, bands)
	if err != nil {
		return err
	}
	if only != "" || len(bands) > 0 {
		fmt.Printf(">> seeding %d group(s), %d user(s)\n", len(groups), len(people))
	}

	// T134 phase 2 (stage C): each band is now seeded by building its CANONICAL v2 directory, packing it
	// to a .tband, and importing it — one path for the demo and real bands. Import FIRST, passwords
	// SECOND (⟨P8⟩): there is NO up-front bulk registration, because pre-creating a member makes the
	// import treat them as consent-required and silently DROP their personal content. The admin is
	// registered per group (the importer, who needs a password); the rest arrive via import and are then
	// given passwords over the public reset flow.
	peopleByUsername := map[string]person{}
	for _, p := range people {
		peopleByUsername[p.username] = p
	}

	seeded := make([]seededGroup, 0, len(groups))
	for _, g := range groups {
		fmt.Printf(">> building %s %q (admin %s)…\n", g.kind, g.name, g.admin)
		sg, err := seedGroupViaImport(addr, password, g, peopleByUsername)
		if err != nil {
			return err
		}
		seeded = append(seeded, sg)
	}

	fmt.Println(">> done.")
	printGuide(addr, password, people, seeded, 0, 0)
	return nil
}

// troubaHome is the runtime root for non-repo data (T129), so live data does not live inside a git
// worktree where `git clean -xdf` can destroy it. TROUBA_HOME wins; else XDG_DATA_HOME/troubastack;
// else ~/.local/share/troubastack. Same formula as the Makefile — keep them in step.
func troubaHome() string {
	if h := os.Getenv("TROUBA_HOME"); h != "" {
		return h
	}
	// A visible ~/troubastack-data (VLL's call) rather than hiding live data deep in ~/.local/share:
	// this holds irreplaceable band libraries, and a folder people can see is a folder people back up.
	return filepath.Join(os.Getenv("HOME"), "troubastack-data")
}

// bandsDirCandidates is the ordered search for the local bands folder (T129). TROUBA_BANDS_DIR wins
// outright. Otherwise the runtime root comes FIRST, so a fresh checkout defaults OUT of the source
// tree; the historical cwd-relative paths follow, so an existing checkout with an in-tree bands/
// keeps working. Pure, so the ordering is unit-tested without touching the filesystem.
func bandsDirCandidates(bandsEnv, home string) []string {
	if bandsEnv != "" {
		return []string{bandsEnv}
	}
	return []string{filepath.Join(home, "bands"), "../bands", "bands", "../../bands", "../../../bands"}
}

func localBandsDir() string {
	for _, c := range bandsDirCandidates(os.Getenv("TROUBA_BANDS_DIR"), troubaHome()) {
		if fi, err := os.Stat(c); err == nil && fi.IsDir() {
			return c
		}
	}
	return ""
}

// bandManifest is a band folder's band.json (bands/<slug>/band.json).
type bandManifest struct {
	Name      string       `json:"name"`
	Shortname string       `json:"shortname"`
	Kind      string       `json:"kind"`
	Notes     string       `json:"notes"`
	Admin     bandMember   `json:"admin"`
	Members   []bandMember `json:"members"`
}
type bandMember struct {
	Username  string `json:"username"`
	Display   string `json:"display"`
	Role      string `json:"role"`
	Conductor bool   `json:"conductor,omitempty"` // promote this member to the app "conductor" role
	// Canonical v2 (T134 stage D): a rewritten folder has no `admin` block and no `display`/
	// `conductor` keys — `displayName` replaces `display`, `role` becomes the PERMISSION enum
	// (admin/conductor/member) and `plays` carries the instrument prose legacy put in `role`.
	// Read BOTH vocabularies here, keyed on the vocabulary and not on formatVersion: the stamp is
	// a claim about a folder, the keys are a fact about it.
	DisplayName string `json:"displayName,omitempty"`
	Plays       string `json:"plays,omitempty"`
}

// permissionRoles are the canonical `role` values. A legacy folder puts instrument prose in the
// same key, so a value outside this set is prose, not a permission.
var permissionRoles = map[string]bool{"admin": true, "conductor": true, "member": true}

// shown returns the member's display name in either vocabulary.
func (m bandMember) shown() string {
	if m.DisplayName != "" {
		return m.DisplayName
	}
	return m.Display
}

// plays returns what the member plays — `plays` canonically, or `role` when that key still holds
// prose (legacy). Never returns a permission enum, so a migrated band cannot end up with a member
// whose instrument reads "admin".
func (m bandMember) plays() string {
	if m.Plays != "" {
		return m.Plays
	}
	if m.Role != "" && !permissionRoles[m.Role] {
		return m.Role
	}
	return ""
}

// isConductor: legacy marks it with a bool, canonical with the role enum.
func (m bandMember) isConductor() bool { return m.Conductor || m.Role == "conductor" }

// adminUsername resolves the band admin in either vocabulary: the legacy `admin` block, else the
// member whose canonical role is "admin". Empty when neither names one.
func (b bandManifest) adminUsername() string {
	if b.Admin.Username != "" {
		return b.Admin.Username
	}
	for _, m := range b.Members {
		if m.Role == "admin" {
			return m.Username
		}
	}
	return ""
}

// selectGroups picks which groups to seed and narrows people to their members:
//
//	band != ""  → exactly the local band whose band.json shortname matches (make band=<shortname>)
//	only != ""  → groups whose name contains the substring (DEMO-VID seeds the orchestra only)
//	neither     → every DEMO group, but SKIP personal bands (they never enter the public demo)
//
// Returns an actionable error when a selector matches nothing. Pure (no I/O) so the demo-isolation
// property is unit-tested without a server.
func selectGroups(groups []groupDef, people []person, only string, bands []string) ([]groupDef, []person, error) {
	needle := strings.ToLower(only)
	// -band is repeatable — each occurrence names ONE band's shortname (make band=myband,otherband
	// splits the list into `-band myband -band otherband`). A stray comma stays part of the literal
	// shortname, so `-band otherband,myband` matches nothing and fails loud below.
	wantBands := map[string]bool{}
	for _, s := range bands {
		if s = strings.TrimSpace(s); s != "" {
			wantBands[s] = true
		}
	}
	bandMode := len(wantBands) > 0
	matchedBand := map[string]bool{}
	kept := groups[:0:0]
	keepUser := map[string]bool{}
	for _, g := range groups {
		var keep bool
		switch {
		case bandMode:
			keep = wantBands[g.shortname]
			if keep {
				matchedBand[g.shortname] = true
			}
		case only != "":
			keep = strings.Contains(strings.ToLower(g.name), needle)
		default:
			keep = !g.personal
		}
		if !keep {
			continue
		}
		kept = append(kept, g)
		keepUser[g.admin] = true
		for _, m := range g.members {
			keepUser[m] = true
		}
	}
	// Fail loud if any requested shortname matched nothing — seeding a partial set (myband
	// but not a mistyped "bnss") silently is a footgun. Names exactly which ones missed.
	if bandMode {
		var missing []string
		for s := range wantBands {
			if !matchedBand[s] {
				missing = append(missing, s)
			}
		}
		if len(missing) > 0 {
			sort.Strings(missing)
			return nil, nil, fmt.Errorf("seed: -band %q matched no band (check bands/*/band.json shortname)", strings.Join(missing, ","))
		}
	}
	if len(kept) == 0 {
		switch {
		case only != "":
			return nil, nil, fmt.Errorf("seed: -only %q matched no groups", only)
		default:
			return nil, nil, fmt.Errorf("seed: no groups to seed")
		}
	}
	filteredPeople := people[:0:0]
	for _, p := range people {
		if keepUser[p.username] {
			filteredPeople = append(filteredPeople, p)
		}
	}
	return kept, filteredPeople, nil
}

// loadLocalBands scans bands/*/band.json and returns one personal groupDef per band (with its
// folder-driven repertoire) plus the people it references. Missing folder → nothing (demo-only
// seed). This is the generic hook that lets any user seed their own band from a local folder.
func loadLocalBands() ([]groupDef, []person, error) {
	dir := localBandsDir()
	if dir == "" {
		return nil, nil, nil
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, nil, err
	}
	var groups []groupDef
	var people []person
	seenUser := map[string]bool{}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		bandDir := filepath.Join(dir, e.Name())
		manPath := filepath.Join(bandDir, "band.json")
		raw, err := os.ReadFile(manPath)
		if err != nil {
			continue // a folder without band.json isn't a band
		}
		var man bandManifest
		if err := json.Unmarshal(raw, &man); err != nil {
			return nil, nil, fmt.Errorf("parse %s: %w", manPath, err)
		}
		shortname := man.Shortname
		if shortname == "" {
			shortname = e.Name() // fall back to the folder name
		}
		// The admin comes from either vocabulary (see adminUsername): a legacy `admin` block, or the
		// member whose canonical role is "admin". Still an error when neither names one.
		adminUser := man.adminUsername()
		if man.Name == "" || adminUser == "" {
			return nil, nil, fmt.Errorf("%s: name and an admin are required "+
				"(an \"admin\" block, or a member with \"role\": \"admin\")", manPath)
		}
		kind := man.Kind
		if kind == "" {
			kind = "Band"
		}
		addPerson := func(m bandMember) {
			if m.Username == "" || seenUser[m.Username] {
				return
			}
			seenUser[m.Username] = true
			people = append(people, person{username: m.Username, display: m.shown(), role: m.plays()})
		}
		addPerson(man.Admin) // legacy only; a canonical folder has no admin block (Username == "")
		memberNames := make([]string, 0, len(man.Members))
		conductor := ""
		for _, m := range man.Members {
			addPerson(m)
			// Canonical folders list the admin among members; legacy ones do not. Either way the
			// admin is carried separately, so it must not also appear in members.
			if m.Username != adminUser {
				memberNames = append(memberNames, m.Username)
			}
			if m.isConductor() {
				conductor = m.Username // who to promote (make band=…)
			}
		}
		songs, err := loadRepertoire(bandDir)
		if err != nil {
			return nil, nil, err
		}
		// T100: the band's concerts, if it defines any. Missing file ⇒ nil ⇒ seeds as before.
		setlists, err := loadSetlists(bandDir, songs)
		if err != nil {
			return nil, nil, err
		}
		groups = append(groups, groupDef{
			name: man.Name, kind: kind, admin: adminUser,
			members: memberNames, songs: songs, setlists: setlists, personal: true, shortname: shortname,
			conductor: conductor, folderPath: bandDir,
		})
	}
	return groups, people, nil
}

// loadSetlists reads <bandDir>/setlists.json into setlistDefs — a local band's concerts (T100).
//
// Shape mirrors the .tband manifest (app.manifestSetlist / manifestItem) so the hand-edited definition
// and the machine snapshot never fork a vocabulary: name, eventDate, venue, notes, and per-item
// keyOverride / tempoOverride / notes / onCall / transposeChords. Two deliberate deviations, both for
// hand-editing: `song` is a REPERTOIRE SLUG (not an internal songID), and ARRAY ORDER replaces an
// explicit `position`.
//
// A missing file is normal — the band seeds exactly as it did before. An unknown slug is a hard error
// naming the slug: silently dropping a song from a gig list is the worst thing this can do.
func loadSetlists(bandDir string, songs []songDef) ([]setlistDef, error) {
	path := filepath.Join(bandDir, "setlists.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil // no concerts defined: not an error
		}
		return nil, err
	}
	var doc struct {
		Setlists []struct {
			Name      string `json:"name"`
			EventDate string `json:"eventDate"`
			Venue     string `json:"venue"`
			Notes     string `json:"notes"`
			Items     []struct {
				Song            string `json:"song"` // a repertoire slug
				KeyOverride     string `json:"keyOverride"`
				TempoOverride   int    `json:"tempoOverride"`
				Notes           string `json:"notes"`
				OnCall          bool   `json:"onCall"`
				TransposeChords bool   `json:"transposeChords"`
			} `json:"items"`
		} `json:"setlists"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	titleBySlug := make(map[string]string, len(songs))
	for _, sd := range songs {
		if sd.slug != "" {
			titleBySlug[sd.slug] = sd.title
		}
	}
	out := make([]setlistDef, 0, len(doc.Setlists))
	for _, sl := range doc.Setlists {
		if strings.TrimSpace(sl.Name) == "" {
			return nil, fmt.Errorf("%s: a setlist has no name", path)
		}
		def := setlistDef{name: sl.Name, eventDate: sl.EventDate, venue: sl.Venue, notes: sl.Notes}
		for _, it := range sl.Items {
			title, ok := titleBySlug[it.Song]
			if !ok {
				// Loud, and it names the slug: a gig list that quietly loses a song is the failure
				// this task exists to prevent.
				return nil, fmt.Errorf("%s: setlist %q references unknown song slug %q (not in repertoire.json)", path, sl.Name, it.Song)
			}
			def.items = append(def.items, overrideDef{
				song: title, keyOverride: it.KeyOverride, tempoOverride: it.TempoOverride,
				notes: it.Notes, onCall: it.OnCall, transposeChords: it.TransposeChords,
			})
		}
		out = append(out, def)
	}
	return out, nil
}

// scorePriority ranks a source PDF for "full score first" ordering within a song:
//
//	0 = the full score (the whole arrangement — the sensible default part),
//	1 = an auxiliary sheet (lyrics/translation/gesture/booklet, or a doc exported to PDF),
//	2 = a single-instrument part (bass, drums, piano, guitar, …).
//
// Matched on the filename, case-insensitively, in French and English (the terms real band
// folders use). Anything with no telltale keyword is treated as the full score.
func scorePriority(path string) int {
	l := strings.ToLower(filepath.Base(path))
	partKeywords := []string{"bass", "basse", "drum", "batterie", "percussion",
		"piano", "guitar", "guitare", "flute", "flûte", "musicien"}
	for _, k := range partKeywords {
		if strings.Contains(l, k) {
			return 2
		}
	}
	auxKeywords := []string{"traduction", "paroles", "gestes", "livret", "lyrics", "resolution", ".docx"}
	for _, k := range auxKeywords {
		if strings.Contains(l, k) {
			return 1
		}
	}
	return 0
}

// loadRepertoire reads <bandDir>/repertoire.json into songDefs, attaching any real source PDFs
// the owner has dropped into <bandDir>/<slug>/. Missing file → no songs.
func loadRepertoire(bandDir string) ([]songDef, error) {
	path := filepath.Join(bandDir, "repertoire.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var rep struct {
		Songs []struct {
			Slug   string   `json:"slug"`
			Title  string   `json:"title"`
			Artist string   `json:"artist"`
			Key    string   `json:"key"`
			Tempo  int      `json:"tempo"`
			Meter  string   `json:"meter"` // T86: the real band-directory entry point; drop it here and a metre vanishes silently
			Notes  string   `json:"notes"`
			Tags   []string `json:"tags"`
		} `json:"songs"`
	}
	if err := json.Unmarshal(raw, &rep); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	out := make([]songDef, 0, len(rep.Songs))
	for _, s := range rep.Songs {
		if s.Title == "" {
			continue
		}
		sd := songDef{title: s.Title, artist: s.Artist, key: s.Key, tempo: s.Tempo, meter: s.Meter, tags: s.Tags, notes: s.Notes, slug: s.Slug}
		if s.Slug != "" {
			pdfs, _ := filepath.Glob(filepath.Join(bandDir, s.Slug, "*.pdf"))
			// Full score first: a song's default part should be the whole arrangement, not a
			// single-instrument or lyrics-only sheet. Rank by scorePriority (score < aux < part),
			// then alphabetically within a rank so the order is stable.
			sort.SliceStable(pdfs, func(i, j int) bool {
				pi, pj := scorePriority(pdfs[i]), scorePriority(pdfs[j])
				if pi != pj {
					return pi < pj
				}
				return pdfs[i] < pdfs[j]
			})
			for _, p := range pdfs {
				base := strings.TrimSuffix(filepath.Base(p), filepath.Ext(p))
				sd.files = append(sd.files, pdfSource{localPath: p, docTitle: base, title: s.Title, subtitle: s.Artist})
			}
			// B15: every <slug>/*.txt (chart-dialect source) becomes its own text-chart part,
			// named after the file — lyrics.txt first (the song's default part), then the rest in
			// sorted order. So a folder can carry Lyrics + Guitar/Bass and reproduce both.
			txts, _ := filepath.Glob(filepath.Join(bandDir, s.Slug, "*.txt"))
			sort.Strings(txts)
			for _, p := range txts {
				if filepath.Base(p) == "lyrics.txt" {
					sd.textCharts = append([]textPart{{path: p, name: "lyrics"}}, sd.textCharts...)
				} else {
					sd.textCharts = append(sd.textCharts, textPart{path: p, name: strings.TrimSuffix(filepath.Base(p), ".txt")})
				}
			}
		}
		out = append(out, sd)
	}
	return out, nil
}

// seededGroup records what was created for the guide.
type seededGroup struct {
	def   groupDef
	songs []string // song titles actually present
}

func registerUser(addr string, p person, password string) error {
	c := newAPIClient(addr)
	err := c.postJSON("/api/auth/register", map[string]string{
		"username": p.username, "displayName": p.display, "password": password,
	}, nil)
	if err == nil {
		fmt.Printf("   + registered %s (%s)\n", p.username, p.display)
		return nil
	}
	if isConflict(err) {
		fmt.Printf("   = %s already exists, skipping\n", p.username)
		return nil
	}
	return fmt.Errorf("register %s: %w", p.username, err)
}

// login returns an authenticated client for username.
func login(addr, username, password string) (*apiClient, error) {
	c := newAPIClient(addr)
	if err := c.postJSON("/api/auth/login", map[string]string{
		"username": username, "password": password,
	}, nil); err != nil {
		return nil, fmt.Errorf("login %s: %w", username, err)
	}
	return c, nil
}

type bandResp struct {
	Band struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"band"`
}

type bandsResp struct {
	Bands []struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"bands"`
}

type inviteResp struct {
	Invite struct {
		ID string `json:"id"`
	} `json:"invite"`
}

type invitesResp struct {
	Invites []struct {
		ID     string `json:"id"`
		BandID string `json:"bandId"`
	} `json:"invites"`
}

type songResp struct {
	Song struct {
		ID    string `json:"id"`
		Title string `json:"title"`
	} `json:"song"`
}

type songsResp struct {
	Songs []struct {
		ID    string `json:"id"`
		Title string `json:"title"`
	} `json:"songs"`
}

type filesResp struct {
	Files []struct {
		ID          string `json:"id"`
		Filename    string `json:"filename"`
		ContentType string `json:"contentType"`
	} `json:"files"`
}

// memberIDs returns a username→userId map for the band plus the admin's user id
// (used as the conductor layer's ownerId).
func memberIDs(admin *apiClient, bandID, adminUsername string) (map[string]string, string, error) {
	var mr membersResp
	if err := admin.getJSON("/api/bands/"+bandID+"/members", &mr); err != nil {
		return nil, "", err
	}
	out := map[string]string{}
	adminID := ""
	for _, m := range mr.Members {
		out[m.User.Username] = m.User.ID
		if m.User.Username == adminUsername {
			adminID = m.User.ID
		}
	}
	return out, adminID, nil
}

func songTitlesOf(admin *apiClient, bandID string) (map[string]string, error) {
	var sr songsResp
	if err := admin.getJSON("/api/bands/"+bandID+"/songs", &sr); err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, s := range sr.Songs {
		out[s.Title] = s.ID
	}
	return out, nil
}

type membersResp struct {
	Members []struct {
		User struct {
			ID       string `json:"id"`
			Username string `json:"username"`
		} `json:"user"`
		Role string `json:"role"`
	} `json:"members"`
}

type setlistResp struct {
	Setlist struct {
		ID string `json:"id"`
	} `json:"setlist"`
}

type setlistsResp struct {
	Setlists []struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"setlists"`
}

type setlistDetailResp struct {
	Items []struct {
		ID     string `json:"id"`
		SongID string `json:"songId"`
	} `json:"items"`
}

type itemResp struct {
	Item struct {
		ID string `json:"id"`
	} `json:"item"`
}

// printGuide writes a human-friendly summary + instructions to stdout.
func printGuide(addr, password string, people []person, groups []seededGroup, fetched, generated int) {
	w := os.Stdout
	line := strings.Repeat("=", 70)
	fmt.Fprintln(w, line)
	fmt.Fprintln(w, "  TROUBASTACK DEMO — READY")
	fmt.Fprintln(w, line)
	fmt.Fprintln(w)

	// Credentials table.
	fmt.Fprintln(w, "  CREDENTIALS  (every password is the same)")
	fmt.Fprintf(w, "  +%s+%s+%s+\n", dash(12), dash(10), dash(34))
	fmt.Fprintf(w, "  | %-10s | %-8s | %-32s |\n", "username", "password", "role")
	fmt.Fprintf(w, "  +%s+%s+%s+\n", dash(12), dash(10), dash(34))
	for _, p := range people {
		fmt.Fprintf(w, "  | %-10s | %-8s | %-32s |\n", p.username, password, p.role)
	}
	fmt.Fprintf(w, "  +%s+%s+%s+\n", dash(12), dash(10), dash(34))
	fmt.Fprintln(w)

	// Structure.
	fmt.Fprintln(w, "  STRUCTURE")
	for _, g := range groups {
		conductor := ""
		if g.def.conductor != "" {
			conductor = "; conductor: " + g.def.conductor
		}
		fmt.Fprintf(w, "  • %s  \"%s\"  (admin: %s; members: %s%s)\n",
			g.def.kind, g.def.name, g.def.admin, strings.Join(g.def.members, ", "), conductor)
		for _, s := range g.def.songs {
			meta := []string{}
			if s.key != "" {
				meta = append(meta, "key "+s.key)
			}
			if s.tempo != 0 {
				meta = append(meta, fmt.Sprintf("%d bpm", s.tempo))
			}
			if len(s.tags) > 0 {
				meta = append(meta, "#"+strings.Join(s.tags, " #"))
			}
			suffix := ""
			if len(meta) > 0 {
				suffix = "  (" + strings.Join(meta, ", ") + ")"
			}
			files := "[PDF + annotations]"
			if len(s.files) > 1 {
				files = fmt.Sprintf("[%d files + annotations]", len(s.files))
			}
			fmt.Fprintf(w, "      - %s%s  %s\n", s.title, suffix, files)
			// Spell out any curated per-member file selections (my-files).
			for username, order := range s.myFilesFor {
				titles := make([]string, 0, len(order))
				for _, idx := range order {
					if idx >= 0 && idx < len(s.files) {
						titles = append(titles, s.files[idx].filename())
					}
				}
				fmt.Fprintf(w, "          • %s's \"my files\": %s\n", username, strings.Join(titles, " → "))
			}
		}
		for _, sl := range g.def.setlists {
			if sl.name == "" {
				continue
			}
			when := sl.eventDate
			if sl.venue != "" {
				when = strings.TrimSpace(when + " @ " + sl.venue)
			}
			n := len(g.def.songs) // demo: the whole group list becomes the setlist
			if len(sl.items) > 0 {
				n = len(sl.items) // T100: an explicit gig list is a SUBSET
			}
			fmt.Fprintf(w, "      ♪ setlist \"%s\" (%s) — %d songs, with key/tempo overrides\n",
				sl.name, when, n)
		}
	}
	fmt.Fprintln(w)

	// PDFs note.
	fmt.Fprintf(w, "  SHEET MUSIC: %d PDF(s) fetched (public domain), %d generated locally.\n", fetched, generated)
	fmt.Fprintln(w, "  Cached under core/cmd/seed/assets/ (gitignored) — re-runs reuse them.")
	fmt.Fprintln(w)

	// What to do.
	fmt.Fprintln(w, "  WHAT TO DO")
	fmt.Fprintln(w, "  1. Open the app:")
	fmt.Fprintln(w, "       • dev/hot-reload SPA :  http://localhost:5173   (make dev)")
	fmt.Fprintf(w, "       • single binary      :  %s   (make run / make demo)\n", addr)
	fmt.Fprintln(w, "  2. Log in as  marie / "+password+"  →  The Troubadours")
	fmt.Fprintln(w, "       'House of the Rising Sun' is a MULTI-FILE song: its shared pool has")
	fmt.Fprintln(w, "       a Guitar tab, a Drums groove, and a rendered chord chart. Leo has a")
	fmt.Fprintln(w, "       curated personal 'my files' selection — just the Guitar tab — so his")
	fmt.Fprintln(w, "       viewer opens to that alone, while bandmates see the default all.")
	fmt.Fprintln(w, "       OPEN 'The Open Road' in the Studio viewer to see its LAYERED")
	fmt.Fprintln(w, "       ANNOTATIONS on the lead sheet: conductor cues (red, mandatory), a")
	fmt.Fprintln(w, "       shared Form/Chorus highlight (amber), and Marie's personal 'My")
	fmt.Fprintln(w, "       notes' (capo, breathe, a circled change). All content is original")
	fmt.Fprintln(w, "       or public-domain (copyright-safe).")
	fmt.Fprintln(w, "       Toggle layers on/off and zoom in.")
	fmt.Fprintln(w, "  3. Log in as  maestro / "+password+"  →  City Chamber Orchestra")
	fmt.Fprintln(w, "       open a piece for the same layered view — plus a player's green")
	fmt.Fprintln(w, "       'Bowing/Breath marks' personal layer instead of chords.")
	fmt.Fprintln(w, "  4. Other members (leo, sasha / flora, cory) already accepted their")
	fmt.Fprintln(w, "       invites — log in as any of them to see the shared band + songs.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  WHAT YOU CAN SET  (all of this works today — no canvas needed)")
	fmt.Fprintln(w, "   • Song page  : key, tempo, tags, notes; upload / rename / reorder / delete files.")
	fmt.Fprintln(w, "   • Band page  : rename, change member roles (admin/conductor/member), remove / leave,")
	fmt.Fprintln(w, "                  list & revoke pending invites.")
	fmt.Fprintln(w, "   • Setlists   : create, add / remove / reorder songs, override key / tempo / notes per song.")
	fmt.Fprintln(w, "   • Viewer     : open any song to see ~3 layered annotation layers (conductor / shared / part);")
	fmt.Fprintln(w, "                  toggle layer visibility and zoom — view-only for now.")
	fmt.Fprintln(w, "   (The seed has already set song metadata, promoted a conductor, built a setlist, and")
	fmt.Fprintln(w, "    imported conductor cues + section markings + a part layer onto each song's PDF.)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "  RESET:  stop the server and  rm -rf troubadata  (wipes users/bands/blobs).")
	fmt.Fprintln(w, line)
}

func dash(n int) string { return strings.Repeat("-", n) }
