package com.troubashare.shared.bundle

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * End-to-end: load the COMMITTED fixtures (generated by `core/cmd/mkbundle`, regen via `make
 * fixtures`) with A02's real loader, proving the generator and the loader agree on the container
 * format (docs/design/08-bundle-container.md). JVM-only (real filesystem), hence androidUnitTest.
 */
class FixtureBundleTest {
    private val loader = BundleLoader()

    /** Real filesystem [BundleFiles] rooted at a fixture directory; load() is called with dir "". */
    private class DiskFiles(private val root: File) : BundleFiles {
        override fun exists(path: String): Boolean = File(root, path).exists()
        override fun readText(path: String): String? = File(root, path).let { if (it.isFile) it.readText() else null }
        override fun sizeOf(path: String): Long = File(root, path).let { if (it.isFile) it.length() else 0L }
    }

    @Test
    fun demoFixture_loadsWithZeroIssues_andExpectedCounts() {
        val result = loader.load("", DiskFiles(fixture("demo")))
        val loaded = assertIs<LoadResult.Loaded>(result)
        assertTrue(loaded.issues.isEmpty(), "demo should have no issues: ${loaded.issues}")

        assertEquals(2, loaded.bundle.songs.size, "songs")
        loaded.bundle.songs.forEach { song ->
            assertEquals(3, song.pages.size, "pages in ${song.songId}")
            song.pages.forEach { page ->
                assertEquals(2, page.overlays.size, "overlays")
                assertEquals(listOf(0, 1), page.overlays.map { it.order }, "overlays sorted by order")
            }
        }
        assertEquals(1uL, loaded.bundle.concertRev)
    }

    @Test
    fun tortureFixtures_matchTheNeverCrashContract() {
        // missing-blob: still loads, the absent raster is flagged (not a failure).
        val mb = assertIs<LoadResult.Loaded>(loader.load("", DiskFiles(fixture("torture/missing-blob"))))
        assertTrue(mb.issues.any { it.kind == BundleIssue.Kind.MISSING_BLOB }, "expected a MISSING_BLOB issue")

        // bad-json: truncated manifest ⇒ Failed.
        assertIs<LoadResult.Failed>(loader.load("", DiskFiles(fixture("torture/bad-json"))))

        // no-manifest: no bundle.json ⇒ Failed with the readable reason.
        val nm = assertIs<LoadResult.Failed>(loader.load("", DiskFiles(fixture("torture/no-manifest"))))
        assertEquals("bundle.json is missing", nm.reason)

        // empty: valid manifest, zero songs ⇒ Loaded, empty.
        val empty = assertIs<LoadResult.Loaded>(loader.load("", DiskFiles(fixture("torture/empty"))))
        assertTrue(empty.bundle.songs.isEmpty())
    }

    /** Locate a committed fixture dir: prefer the test classpath, fall back to the source tree. */
    private fun fixture(rel: String): File {
        val res = javaClass.classLoader?.getResource("fixtures/demo/bundle.json")
        if (res != null && res.protocol == "file") {
            val fixturesDir = File(res.toURI()).parentFile?.parentFile // .../fixtures
            val f = fixturesDir?.let { File(it, rel) }
            if (f != null && f.isDirectory) return f
        }
        val cwd = System.getProperty("user.dir")
        for (base in listOf("src/commonTest/resources", "shared/src/commonTest/resources", "app/shared/src/commonTest/resources")) {
            val f = File(cwd, "$base/fixtures/$rel")
            if (f.isDirectory) return f
        }
        fail("fixture '$rel' not found (cwd=$cwd)")
    }
}
