// Code generated by cmd/gen-mirrors from proto/troubastack/v1/bundle.proto. DO NOT EDIT.
// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it).

package bake

// PageImages mirrors proto troubastack.v1.PageImages.
type PageImages struct {
	PageRasterRef         string       `json:"pageRasterRef,omitempty"`
	RasterHash            string       `json:"rasterHash,omitempty"`
	Overlays              []LayerImage `json:"overlays,omitempty"`
	ContentBottomPermille int32        `json:"contentBottomPermille,omitempty"`
}

// LayerImage mirrors proto troubastack.v1.LayerImage.
type LayerImage struct {
	LayerID     string `json:"layerId,omitempty"`
	ImageRef    string `json:"imageRef,omitempty"`
	ContentHash string `json:"contentHash,omitempty"`
	Order       int32  `json:"order,omitempty"`
	Mandatory   bool   `json:"mandatory,omitempty"`
	RoleTag     string `json:"roleTag,omitempty"`
	Name        string `json:"name,omitempty"`
	Owner       string `json:"owner,omitempty"`
	DefaultOn   *bool  `json:"defaultOn,omitempty"`
}

// BakedSong mirrors proto troubastack.v1.BakedSong.
type BakedSong struct {
	SongID         string        `json:"songId,omitempty"`
	SourceRevision uint64        `json:"sourceRevision,string,omitempty"`
	SongRev        uint64        `json:"songRev,string,omitempty"`
	Pages          []PageImages  `json:"pages,omitempty"`
	DisplayNotes   string        `json:"displayNotes,omitempty"`
	Key            string        `json:"key,omitempty"`
	Tempo          int32         `json:"tempo,omitempty"`
	OnCall         bool          `json:"onCall,omitempty"`
	Title          string        `json:"title,omitempty"`
	Cues           []SongCue     `json:"cues,omitempty"`
	MemberCues     []MemberCues  `json:"memberCues,omitempty"`
	Meter          string        `json:"meter,omitempty"`
	Artist         string        `json:"artist,omitempty"`
	MemberPages    []MemberPages `json:"memberPages,omitempty"`
}

// MemberCues mirrors proto troubastack.v1.MemberCues.
type MemberCues struct {
	MemberID string    `json:"memberId,omitempty"`
	Cues     []SongCue `json:"cues,omitempty"`
}

// MemberPages mirrors proto troubastack.v1.MemberPages.
type MemberPages struct {
	MemberID string  `json:"memberId,omitempty"`
	Page     []int32 `json:"page,omitempty"`
}

// SongCue mirrors proto troubastack.v1.SongCue.
type SongCue struct {
	Icon  string `json:"icon,omitempty"`
	Color string `json:"color,omitempty"`
}

// ConcertBundle mirrors proto troubastack.v1.ConcertBundle.
type ConcertBundle struct {
	ConcertID   string         `json:"concertId,omitempty"`
	Name        string         `json:"name,omitempty"`
	ConcertRev  uint64         `json:"concertRev,string,omitempty"`
	BakedAt     int64          `json:"bakedAt,string,omitempty"`
	BakedBy     string         `json:"bakedBy,omitempty"`
	FinalLocked bool           `json:"finalLocked,omitempty"`
	Songs       []BakedSong    `json:"songs,omitempty"`
	Roster      []BundleMember `json:"roster,omitempty"`
	BandID      string         `json:"bandId,omitempty"`
	BandName    string         `json:"bandName,omitempty"`
}

// BundleMember mirrors proto troubastack.v1.BundleMember.
type BundleMember struct {
	MemberID    string `json:"memberId,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Role        string `json:"role,omitempty"`
}
