// Code generated by cmd/gen-mirrors from proto/troubastack/v1/object.proto. DO NOT EDIT.
// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it).

package domain

// ObjectTypeToString maps an ObjectType to its canonical wire string
// (TypeUnspecified / unknown → "").
func ObjectTypeToString(t ObjectType) string {
	switch t {
	case TypeFreehand:
		return "freehand"
	case TypeLine:
		return "line"
	case TypeRect:
		return "rect"
	case TypeEllipse:
		return "ellipse"
	case TypeText:
		return "text"
	case TypeHighlight:
		return "highlight"
	case TypeIcon:
		return "icon"
	default:
		return ""
	}
}

// ObjectTypeFromString maps a wire string to its ObjectType
// (unknown → TypeUnspecified).
func ObjectTypeFromString(s string) ObjectType {
	switch s {
	case "freehand":
		return TypeFreehand
	case "line":
		return TypeLine
	case "rect":
		return TypeRect
	case "ellipse":
		return TypeEllipse
	case "text":
		return TypeText
	case "highlight":
		return TypeHighlight
	case "icon":
		return TypeIcon
	default:
		return TypeUnspecified
	}
}
