// Code generated by cmd/gen-mirrors from proto/troubastack/v1/bundle.proto. DO NOT EDIT.
// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it).

/** SongCue mirrors proto troubastack.v1.SongCue. */
export type SongCue = {
  icon?: string;
  color?: string;
};
