// Code generated by cmd/gen-mirrors from proto/troubastack/v1/bundle.proto. DO NOT EDIT.
// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it). The 64-bit
// KSerializers at the bottom are generated machinery too — fix them in the generator,
// never here. Serialization is proto3 canonical JSON: lowerCamelCase names (property ==
// JSON name), int64/uint64 as JSON strings, int32 as a number, every field defaulted.
package com.troubastack.shared.bundle

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonPrimitive

/** proto troubastack.v1.PageImages. */
@Serializable
data class PageImages(
    val pageRasterRef: String = "",
    val rasterHash: String = "",
    val overlays: List<LayerImage> = emptyList(),
    val contentBottomPermille: Int = 0,
)

/** proto troubastack.v1.LayerImage. */
@Serializable
data class LayerImage(
    val layerId: String = "",
    val imageRef: String = "",
    val contentHash: String = "",
    val order: Int = 0,
    val mandatory: Boolean = false,
    val roleTag: String = "",
    val name: String = "",
    val owner: String = "",
    val defaultOn: Boolean? = null,
)

/** proto troubastack.v1.BakedSong. */
@Serializable
data class BakedSong(
    val songId: String = "",
    @Serializable(with = ProtoUInt64Serializer::class) val sourceRevision: ULong = 0uL,
    @Serializable(with = ProtoUInt64Serializer::class) val songRev: ULong = 0uL,
    val pages: List<PageImages> = emptyList(),
    val displayNotes: String = "",
    val key: String = "",
    val tempo: Int = 0,
    val onCall: Boolean = false,
    val title: String = "",
    val cues: List<SongCue> = emptyList(),
    val memberCues: List<MemberCues> = emptyList(),
    val meter: String = "",
    val artist: String = "",
    val memberPages: List<MemberPages> = emptyList(),
    val kind: String = "",
    val label: String = "",
)

/** proto troubastack.v1.MemberCues. */
@Serializable
data class MemberCues(
    val memberId: String = "",
    val cues: List<SongCue> = emptyList(),
)

/** proto troubastack.v1.MemberPages. */
@Serializable
data class MemberPages(
    val memberId: String = "",
    val page: List<Int> = emptyList(),
)

/** proto troubastack.v1.SongCue. */
@Serializable
data class SongCue(
    val icon: String = "",
    val color: String = "",
)

/** proto troubastack.v1.ConcertBundle. */
@Serializable
data class ConcertBundle(
    val concertId: String = "",
    val name: String = "",
    @Serializable(with = ProtoUInt64Serializer::class) val concertRev: ULong = 0uL,
    @Serializable(with = ProtoInt64Serializer::class) val bakedAt: Long = 0L,
    val bakedBy: String = "",
    val finalLocked: Boolean = false,
    val songs: List<BakedSong> = emptyList(),
    val roster: List<BundleMember> = emptyList(),
    val bandId: String = "",
    val bandName: String = "",
)

/** proto troubastack.v1.BundleMember. */
@Serializable
data class BundleMember(
    val memberId: String = "",
    val displayName: String = "",
    val role: String = "",
)

/** proto troubastack.v1.AvailableConcert. */
@Serializable
data class AvailableConcert(
    val concertId: String = "",
    val name: String = "",
    @Serializable(with = ProtoUInt64Serializer::class) val currentRev: ULong = 0uL,
    @Serializable(with = ProtoInt64Serializer::class) val updatedAt: Long = 0L,
    val finalLocked: Boolean = false,
    val songs: List<SongRev> = emptyList(),
) {

    /** proto troubastack.v1.AvailableConcert.SongRev. */
    @Serializable
    data class SongRev(
        val songId: String = "",
        @Serializable(with = ProtoUInt64Serializer::class) val rev: ULong = 0uL,
    )
}

/** proto troubastack.v1.AvailableConcerts. */
@Serializable
data class AvailableConcerts(
    val concerts: List<AvailableConcert> = emptyList(),
)

// --- proto3 canonical-JSON scalar serializers (generated machinery — fix in the generator) ---
// int64/uint64 travel as JSON strings in canonical proto3 JSON. These read the canonical
// string form and also tolerate a bare JSON number (lenient input). A non-numeric value
// throws inside kotlinx decoding, which BundleLoader.load catches and turns into a Failed
// value — it never escapes the loader.

/** uint64 <-> JSON string. */
internal object ProtoUInt64Serializer : KSerializer<ULong> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("troubastack.uint64", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: ULong) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder): ULong = decoder.scalarString().toULong()
}

/** int64 <-> JSON string. */
internal object ProtoInt64Serializer : KSerializer<Long> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("troubastack.int64", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: Long) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder): Long = decoder.scalarString().toLong()
}

/** Read a 64-bit scalar as a string, accepting both "123" (canonical) and 123 (lenient). */
private fun Decoder.scalarString(): String =
    if (this is JsonDecoder) {
        (decodeJsonElement() as? JsonPrimitive
            ?: throw SerializationException("expected a scalar for a 64-bit integer")).content
    } else {
        decodeString()
    }
