// Code generated by cmd/gen-mirrors from proto/troubastack/v1/object.proto. DO NOT EDIT.
// Regenerate: `cd core && go run ./cmd/gen-mirrors` (CI drift-guards it).

/** The wire object-type set — mirrors proto ObjectType. */
export type ObjectType =
  | "freehand"
  | "line"
  | "rect"
  | "ellipse"
  | "text"
  | "highlight"
  | "icon";
